<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241007050354 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE book_copy (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rented BOOLEAN NOT NULL, book_id INT NOT NULL, owner_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5427F08A16A2B381 ON book_copy (book_id)');
        $this->addSql('CREATE INDEX IDX_5427F08A7E3C61F9 ON book_copy (owner_id)');
        $this->addSql('CREATE TABLE books (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, isbn VARCHAR(255) NOT NULL, category VARCHAR(255) DEFAULT NULL, author VARCHAR(255) NOT NULL, publication_year DATE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, enabled BOOLEAN NOT NULL, created_by_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4A1B2A92B03A8386 ON books (created_by_id)');
        $this->addSql('CREATE TABLE rent (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rent_date DATE NOT NULL, return_date DATE NOT NULL, enabled BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, book_copy_id INT NOT NULL, lender_user_id INT NOT NULL, receptor_user_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2784DCC3B550FE4 ON rent (book_copy_id)');
        $this->addSql('CREATE INDEX IDX_2784DCC1ABE9DC4 ON rent (lender_user_id)');
        $this->addSql('CREATE INDEX IDX_2784DCC4A81C52 ON rent (receptor_user_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, course VARCHAR(255) NOT NULL, institution VARCHAR(255) NOT NULL, username VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('ALTER TABLE book_copy ADD CONSTRAINT FK_5427F08A16A2B381 FOREIGN KEY (book_id) REFERENCES books (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE book_copy ADD CONSTRAINT FK_5427F08A7E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE books ADD CONSTRAINT FK_4A1B2A92B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE rent ADD CONSTRAINT FK_2784DCC3B550FE4 FOREIGN KEY (book_copy_id) REFERENCES book_copy (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE rent ADD CONSTRAINT FK_2784DCC1ABE9DC4 FOREIGN KEY (lender_user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE rent ADD CONSTRAINT FK_2784DCC4A81C52 FOREIGN KEY (receptor_user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE book_copy DROP CONSTRAINT FK_5427F08A16A2B381');
        $this->addSql('ALTER TABLE book_copy DROP CONSTRAINT FK_5427F08A7E3C61F9');
        $this->addSql('ALTER TABLE books DROP CONSTRAINT FK_4A1B2A92B03A8386');
        $this->addSql('ALTER TABLE rent DROP CONSTRAINT FK_2784DCC3B550FE4');
        $this->addSql('ALTER TABLE rent DROP CONSTRAINT FK_2784DCC1ABE9DC4');
        $this->addSql('ALTER TABLE rent DROP CONSTRAINT FK_2784DCC4A81C52');
        $this->addSql('DROP TABLE book_copy');
        $this->addSql('DROP TABLE books');
        $this->addSql('DROP TABLE rent');
        $this->addSql('DROP TABLE "user"');
    }
}
