<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240920045207 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE rent (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rent_date DATE NOT NULL, return_date DATE NOT NULL, book_copy_id INT NOT NULL, lender_user_id INT NOT NULL, receptor_user_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2784DCC3B550FE4 ON rent (book_copy_id)');
        $this->addSql('CREATE INDEX IDX_2784DCC1ABE9DC4 ON rent (lender_user_id)');
        $this->addSql('CREATE INDEX IDX_2784DCC4A81C52 ON rent (receptor_user_id)');
        $this->addSql('ALTER TABLE rent ADD CONSTRAINT FK_2784DCC3B550FE4 FOREIGN KEY (book_copy_id) REFERENCES books (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE rent ADD CONSTRAINT FK_2784DCC1ABE9DC4 FOREIGN KEY (lender_user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE rent ADD CONSTRAINT FK_2784DCC4A81C52 FOREIGN KEY (receptor_user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE rent DROP CONSTRAINT FK_2784DCC3B550FE4');
        $this->addSql('ALTER TABLE rent DROP CONSTRAINT FK_2784DCC1ABE9DC4');
        $this->addSql('ALTER TABLE rent DROP CONSTRAINT FK_2784DCC4A81C52');
        $this->addSql('DROP TABLE rent');
    }
}
